// <auto-generated />
using System;
using BackAgosto.Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackAgosto.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackAgosto.Entidades.DetalleInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("InventarioId")
                        .HasColumnType("integer");

                    b.Property<string>("area")
                        .HasColumnType("text");

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("codigo")
                        .HasColumnType("text");

                    b.Property<string>("detalle")
                        .HasColumnType("text");

                    b.Property<string>("equipo")
                        .HasColumnType("text");

                    b.Property<int>("nro")
                        .HasColumnType("integer");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.Property<string>("oficina")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventarioId");

                    b.ToTable("DetalleInventario");
                });

            modelBuilder.Entity("BackAgosto.Entidades.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("nombreInventario")
                        .HasColumnType("text");

                    b.Property<string>("tipoInventario")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("BackAgosto.Entidades.DetalleInventario", b =>
                {
                    b.HasOne("BackAgosto.Entidades.Inventario", "Inventario")
                        .WithMany("detallesDelInventario")
                        .HasForeignKey("InventarioId");

                    b.Navigation("Inventario");
                });

            modelBuilder.Entity("BackAgosto.Entidades.Inventario", b =>
                {
                    b.Navigation("detallesDelInventario");
                });
#pragma warning restore 612, 618
        }
    }
}
